name: release from changelog

on:
  push:
    tags:
      - \d+.\d+.\d+

jobs:
  release_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate GitHub Release
        uses: lsegal/github-release-from-changelog-action@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUT_TITLE: $tag
